name: CI
on: [push,pull_request]

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Lint Tests
        uses: borales/actions-yarn@v4
        with:
          cmd: lint

      - name: Run Unit Tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test